name: Build Android APK

on:
  push:
    branches:
      - main  # This triggers the workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java 8 for Gradle
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      # Step 3: Grant permission to Gradle wrapper
      - name: Grant permission to Gradle wrapper
        run: chmod +x android/gradlew

      # Step 4: Build APK using Gradle
      - name: Build APK
        run: |
          cd android
          ./gradlew clean assembleRelease

      # Step 5: Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
